name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Build and test
        run: mvn verify
      - name: Generate SBOM
        run: mvn -pl services/ingress cyclonedx:makeAggregateBom
      - name: Container build scan
        run: |
          docker buildx build --load -f services/ingress/Dockerfile -t ingress:test .
          docker scout cves ingress:test || true
